### ISSUE TITLE
Stackage

### ISSUE THREAD

**Issue by jprupp** [serokell/rocksdb-haskell#12]
I am the author of the [Haskoin](https://github.com/haskoin) suite. I would like to get the Haskoin Node and Store packages into Stackage, but for that I need to include this package. Would you allow me to become the maintainer of `rocksdb-haskell` on Stackage?

**Comment by gromakovsky** [comment]
If by that you mean simply adding `rocksdb-haskell` under your name into `build-constraints.yaml`, then no problem, feel free to do it.
If you mean something different, please clarify what exactly.

**Comment by jprupp** [comment]
It is just adding `rocksdb-haskell` under my name into `build-constraints.yaml`. It will soon be available to LTS Haskell users, as I have already done it.
