### ISSUE TITLE
Binary/Cereal

### ISSUE THREAD

**Issue by orionsread** [serokell/rocksdb-haskell#4]
Why do you use binary rather than cereal, given that you are now doing an extra conversion between strict and lazy ByteStrings?

**Comment by gromakovsky** [comment]
Good point. `binary` isn't used internally, there are only some helper functions which use it. They are helpful when your whole application uses `binary` for serialization (which was true for us earlier).
I think those helpers should be removed and dependency on `binary` should be dropped.

**Comment by gromakovsky** [comment]
Btw, in our application we don't use binary anymore, we are using `cborg`.
